### ISSUE TITLE
about 17 dimensional skeleton detection code

### ISSUE THREAD

**Issue by zdl12345678** [talreiss/Accurate-Interpretable-VAD#1]
Hi, your work is excellent. Can you provide 17 dimensional skeleton detection code? I want to train my dataset.

best

**Comment by talreiss** [comment]
Hi,

Thank you for taking an interest in our work. 
The pose extraction process will be released soon, but for now I suggest either downloading the pose representations provided by us from [this link](https://drive.google.com/drive/u/1/folders/1vSMpDb5jIyc2tNJaYVphguUlFcwPayms), or simply use the AlphaPose implementation from [here](https://github.com/MVIG-SJTU/AlphaPose).

Tal

**Comment by kienptitit** [comment]
@talreiss 
Hi,
Could you explain the meaning of the shape feature to me?

**Comment by sysu19351115** [comment]
Hi,
Your work is excellent. I am also looking forward to your official skeleton detection code.

best

**Comment by talreiss** [comment]
Hi,

The pose extraction code will be released in the future, as I mentioned before. We will update when it is released.

**Comment by talreiss** [comment]
Currently, we don't plan to release the pose feature pipeline. But, since we're just using AlphaPose without any tricks, it should be easy to re-implement.
