### ISSUE TITLE
extract all test objects from Ped2

### ISSUE THREAD

**Issue by LBAMAD** [talreiss/Accurate-Interpretable-VAD#11]
Hi,your work is excellent! I have a question for you.When I executed the command "python pre_processing/bboxes.py --dataset_name=ped2",the following error occurred.

/opt/conda/lib/python3.7/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
 60%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                                              | 1200/2010 [01:39<01:06, 12.10it/s]
Traceback (most recent call last):
  File "pre_processing/bboxes.py", line 163, in <module>
    extract(dataset_root=root, dataset_name=args.dataset_name, train=args.train)
  File "pre_processing/bboxes.py", line 125, in extract
    batch, _ = dataset.__getitem__(idx)
  File "./video_dataset.py", line 240, in __getitem__
    cur_img = np.transpose(cv2.imread(self.frame_addresses[i]), [2, 0, 1])
  File "<__array_function__ internals>", line 6, in transpose
  File "/opt/conda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 658, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/opt/conda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 55, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: axes don't match array

Hope to get your answer，thanks！

**Comment by Haifu-Ye** [comment]
> Hi,your work is excellent! I have a question for you.When I executed the command "python pre_processing/bboxes.py --dataset_name=ped2",the following error occurred.
> 
> /opt/conda/lib/python3.7/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:2895.) return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined] 60%|█████████████████████████████████████████████████████████████████████████████████████████████▏ | 1200/2010 [01:39<01:06, 12.10it/s] Traceback (most recent call last): File "pre_processing/bboxes.py", line 163, in extract(dataset_root=root, dataset_name=args.dataset_name, train=args.train) File "pre_processing/bboxes.py", line 125, in extract batch, _ = dataset.**getitem**(idx) File "./video_dataset.py", line 240, in **getitem** cur_img = np.transpose(cv2.imread(self.frame_addresses[i]), [2, 0, 1]) File "<**array_function** internals>", line 6, in transpose File "/opt/conda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 658, in transpose return _wrapfunc(a, 'transpose', axes) File "/opt/conda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 55, in _wrapfunc return _wrapit(obj, method, *args, **kwds) File "/opt/conda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 44, in _wrapit result = getattr(asarray(obj), method)(*args, **kwds) ValueError: axes don't match array
> 
> Hope to get your answer，thanks！

hi！I want to try to use the shanghaitech dataset, but it seems that the format of the dataset in extract_shanghaitech_frames.py is not the same as that of the official shanghaitech dataset, however, the download link for the shanghaitech dataset in the script doesn't work, and I'd like to know how other people I would like to know how you solve this problem. Thank you!
