### ISSUE TITLE
FlowNet2 environment

### ISSUE THREAD

**Issue by molu-ggg** [talreiss/Accurate-Interpretable-VAD#12]
Dear authors,
Hello, I have a question, in the reproduction of 2.Optical Flow when there are some problems. According to your environment, on my linux 1080ti, execute `python pre_processing / flows.py-dataset_name = ped2-train `
```
The error in correlation _ forward _ cuda _ kernel : invalid device function, 
runtimeError : CUDA call failed problem,
```
 I guess it is a FlowNet2 problem, so go to the FlowNet2 official website to use the environment it provides, but the environment version is too low to be compatible with your code. Is there any good solution ?
I would appreciate it if you could answer. Thank you !

**Comment by talreiss** [comment]
Hi,
Please follow the instructions carefully step by step as we did not encounter this problem. I tried to reinstall everything and it worked. I hope this helps.

Tal
