### ISSUE TITLE
1:1 Mapping Human Poses and Detector Output

### ISSUE THREAD

**Issue by jakubmicorek** [talreiss/Accurate-Interpretable-VAD#14]
Hi!

As I delved deeper into the code, it seems that the provided pose features have no apparent correlation with the bounding boxes. Specifically, in a single frame with multiple detections, such as persons and vehicles, it's challenging to discern which pose corresponds to which person within the frame.

Is there a straightforward method to directly link each human pose to the corresponding individual identified by the detector? 
Could you provide the poses in the same format as the CLIP/velocities where the relations are present?

Thank you

**Comment by talreiss** [comment]
Unfortunately, the files we provided are invertible. To perform 1:1 mapping, you would need to run from scratch and modify the files as necessary.
