### ISSUE TITLE
我尝试运行bash install_flownet2.sh，但是出现TypeError: expected string or bytes-like object，好像是 cmdclass={         'build_ext': BuildExtension     })这里有问题

### ISSUE THREAD

**Issue by walking-malloc** [talreiss/Accurate-Interpretable-VAD#16]

**Comment by talreiss** [comment]
The implementation we offer is based upon FlowNet2 and its implementation. If you have any implementation-related questions, please refer to the original FlowNet2 [repository](https://github.com/NVIDIA/flownet2-pytorch).

**Comment by Haifu-Ye** [comment]
> _No description provided._

我想尝试使用shanghaitech数据集，但是似乎extract_shanghaitech_frames.py里面数据集的格式与shanghaitech官方数据集的格式不一样，然而脚本里面shanghaitech数据集的下载链接失效了，我想知道其他人是怎么解决这个问题的。这个论文应该是对数据集处理过了的，直接用原来的数据用不了
