### ISSUE TITLE
Unable to download avenue dataset using avenue.sh 

### ISSUE THREAD

**Issue by KHariHaraChaitanya** [talreiss/Accurate-Interpretable-VAD#17]
I tried executing avenue.sh and found that url http://101.32.75.151:8181/dataset/avenue.tar.gz is taking too long time to respond. Could you please update this with latest url? or point me to right url for downloading manually?

**Comment by talreiss** [comment]
Unfortunately, this link is not supported by us. Here is the official webpage of the dataset, which provides an alternative link: 
https://www.cse.cuhk.edu.hk/leojia/projects/detectabnormal/dataset.html
