### ISSUE TITLE
Where can i dowload the dataset?

### ISSUE THREAD

**Issue by abrarsharif66** [talreiss/Accurate-Interpretable-VAD#18]

**Comment by talreiss** [comment]
Please follow the guidelines in [this link](https://github.com/talreiss/Accurate-Interpretable-VAD/tree/master/data).
However, the links provided there are not supported by us, so if a link is broken, I suggest visiting the official datasets webpages.

Tal

**Comment by Haifu-Ye** [comment]
> Please follow the guidelines in [this link](https://github.com/talreiss/Accurate-Interpretable-VAD/tree/master/data). However, the links provided there are not supported by us, so if a link is broken, I suggest visiting the official datasets webpages.
> 
> Tal

hi！I want to try to use the shanghaitech dataset, but it seems that the format of the dataset in extract_shanghaitech_frames.py is not the same as that of the official shanghaitech dataset, however, the download link for the shanghaitech dataset in the script doesn't work, and I'd like to know how other people I would like to know how other people solve this problem.
