### ISSUE TITLE
no such file: train_clip_length.npy

### ISSUE THREAD

**Issue by yizuo417** [talreiss/Accurate-Interpretable-VAD#19]
when i run the score_calibration.py  rasie :
FileNotFoundError: [Errno 2] No such file or directory: 'data/avenue/train_clip_lengths.npy'
any one can solve it?

**Comment by yizuo417** [comment]
also 'test_clip_lengths.npy'

**Comment by talreiss** [comment]
https://github.com/talreiss/Accurate-Interpretable-VAD/issues/15
