### ISSUE TITLE
Results on Street Scene benchmark?

### ISSUE THREAD

**Issue by Sino0904** [talreiss/Accurate-Interpretable-VAD#2]
Hello,

Great work! I was wondering if you also evaluated you method on Street Scene Benchmark?

Paper: https://openaccess.thecvf.com/content_WACV_2020/papers/Ramachandra_Street_Scene_A_new_dataset_and_evaluation_protocol_for_video_WACV_2020_paper.pdf

Dataset: https://www.merl.com/demos/video-anomaly-detection

**Comment by talreiss** [comment]
Hi,
We haven't tested our method on this benchmark yet, but we encourage you to do so and let us know how it works :)

Tal
