### ISSUE TITLE
can't link dataset url  http://101.32.75.151:8181

### ISSUE THREAD

**Issue by TheExileCoder** [talreiss/Accurate-Interpretable-VAD#21]
http://101.32.75.151:8181/dataset/ped2.tar.gz not work, how to get the dataset ?  thanks!

**Comment by TheExileCoder** [comment]
http://www.svcl.ucsd.edu/projects/anomaly/dataset.htm, i find ped2 here, is your dataset same to the original dataset?

**Comment by talreiss** [comment]
Yes, it is.

**Comment by TheExileCoder** [comment]
factly, it is not, i found it here finally. ^o^
 https://drive.usercontent.google.com/download?id=1PO5BCMHUnmyb4NRSBFu28squcDv5VWTR&export=download&authuser=0&confirm=t&uuid=3cd36281-4436-4a42-b2ce-4cd261ad56a9&at=APZUnTUy-MtomLNEU2kED2VfL04p%3A1716970944905

**Comment by Haifu-Ye** [comment]
hi！I want to try to use the shanghaitech dataset, but it seems that the format of the dataset in extract_shanghaitech_frames.py is not the same as that of the official shanghaitech dataset, however, the download link for the shanghaitech dataset in the script doesn't work, and I'd like to know how other people I would like to know how you solve this problem. Thank you!

> factly, it is not, i found it here finally. ^o^ https://drive.usercontent.google.com/download?id=1PO5BCMHUnmyb4NRSBFu28squcDv5VWTR&export=download&authuser=0&confirm=t&uuid=3cd36281-4436-4a42-b2ce-4cd261ad56a9&at=APZUnTUy-MtomLNEU2kED2VfL04p%3A1716970944905
