### ISSUE TITLE
how long does the bboxes.py running?

### ISSUE THREAD

**Issue by TheExileCoder** [talreiss/Accurate-Interpretable-VAD#22]
i train ped2 bboxes by commond 

` python pre_processing/bboxes.py --dataset_name=ped2 --train
` 
 
and it has run **20 hours** without any tips or logs like this, is it all right?

![image](https://github.com/talreiss/Accurate-Interpretable-VAD/assets/61927003/64b19bb8-562f-43a2-a161-9f69d1163709)

**Comment by talreiss** [comment]
I guess you're running it on CPU, so it should be very fast on GPU

**Comment by TheExileCoder** [comment]
> I guess you're running it on CPU, so it should be very fast on GPU

which GPU version (3090, 3080 ...) did you use in this project?

**Comment by talreiss** [comment]
I used RTX2080, not sure what version you mean.

**Comment by TheExileCoder** [comment]
I know, just it, thank you.
