### ISSUE TITLE
No visualisation on the poses described in the paper is available.

### ISSUE THREAD

**Issue by kobayashi-normal-github** [talreiss/Accurate-Interpretable-VAD#23]
Based on "https://arxiv.org/pdf/2212.00789v1", an attempt was made to draw a red bounding box for the element most affected by the pose data in each frame.
As a result, the provided normalised pose information alone could not be used to correctly draw the bounding box.

Therefore, please provide the pose.npy file before the normalisation process.

**Comment by talreiss** [comment]
Unfortunately, we no longer have this information.

**Comment by Haifu-Ye** [comment]
> Based on "https://arxiv.org/pdf/2212.00789v1", an attempt was made to draw a red bounding box for the element most affected by the pose data in each frame. As a result, the provided normalised pose information alone could not be used to correctly draw the bounding box.
> 
> Therefore, please provide the pose.npy file before the normalisation process.

hi！I want to try to use the shanghaitech dataset, but it seems that the format of the dataset in extract_shanghaitech_frames.py is not the same as that of the official shanghaitech dataset, however, the download link for the shanghaitech dataset in the script doesn't work, and I'd like to know how other people I would like to know how you solve this problem. Thank you!
