### ISSUE TITLE
Object detection model

### ISSUE THREAD

**Issue by nuclearboy95** [talreiss/Accurate-Interpretable-VAD#5]
Thanks for sharing your wonderful work.

I have a minor question.
Your paper on arXiv says that you used Mask R-CNN for detection bounding boxes in videos.
But as far as I know, it is used for segmentation.
Wasn't it Faster R-CNN ?

**Comment by talreiss** [comment]
Hi,

We used Mask R-CNN without the segmentation component, with [this](https://github.com/facebookresearch/detectron2/blob/main/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml) configuration. It was only used to extract bounding boxes. You're right, it can indeed be replaced with Faster R-CNN.

**Comment by nuclearboy95** [comment]
I see. Thanks a lot!
