### ISSUE TITLE
Anomaly Scores

### ISSUE THREAD

**Issue by sharkDDD** [talreiss/Accurate-Interpretable-VAD#7]
https://github.com/talreiss/Accurate-Interpretable-VAD/blob/e02bdd70d976749637898e0aaf46313cc2399194/evaluate.py#L118

Hi, your work is excellent.  I have a question about the anomaly score calculation.

In the paper, the anomaly score is calculated through Eq(5), but in the code, the anomaly score for ShanghaiTech does not contain the deep features component.

Your work has greatly inspired me, so I hope you can help me solve the above issue, thanks!

**Comment by talreiss** [comment]
Hi,

A breakdown of our component results can be found in Tab.3 of the paper. We used the best performing combination (pose+velocity, 85.9% micro AUROC) in the code. We encourage you to make changes to this scoring if you desire (to get 85.1 micro AUROC).
